#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1

# bspc rule -a "program" <comandos>
# comandos: ->
# state=floating follow=on
# desktop='^2'
# manage=off
bspc rule -a Thunar state=floating
bspc rule -a Navigator desktop='^2' follow=on
bspc rule -a firefox-esr desktop='^2' follow=on
bspc rule -a waterfox desktop='^2' follow=on
bspc rule -a install4j-burp-StartBurp state=floating 
bspc rule -a burpsuite state=floating 
bspc rule -a burp-StartBurp state=floating 
bspc rule -a Wireshark state=floating
bspc rule -a kitty state=floating rectangle=600x400+300+250
#  terminal Kitty, se abrirá en modo flotante con un tamaño de 800x600 píxeles, ubicada a 100 píxeles desde el borde izquierdo y 100 píxeles desde el borde superior de la pantalla.
bspc rule -a Display-im6.q16 state=floating

# bspc
# $( xprop ) para obtener información de la ventana

feh --bg-fill ~/Documents/Entorno/LinuxConfig/Wallpapers/cat_min.png &

bash ~/.config/polybar/launch.sh --blocks &

picom --config ~/.config/picom/picom.conf &
# Solution for picom error
# picom --config ~/.config/picom/picom.conf --daemon &
setxkbmap latam

bspc config border_width         4
# bspc config focused_border_color "#bb9af7"
bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#282e3a"

xrandr --output Virtual1 --mode 1920x1080
