#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V 

#bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config focused_border_color '#1f1f1f'
bspc config presel_feedback_color '#4f75e0'



bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
# bspc rule -a burp-StartBurp state=floating

feh --bg-fill /home/bytehxz/Documents/Entorno/LinuxConfig/Wallpapers/rose_fire.jpg &

# bash ~/.config/polybar/launch.sh --cuts &
# bash ~/.config/polybar/launch.sh --hack &
# bash ~/.config/polybar/launch.sh --blocks &
bash ~/.config/polybar/launch.sh --docky &
# picom & 

picom --config ~/.config/picom/picom.conf &
# bspc config active_border_color "#8bcc6a"
# bspc config normal_border_color "#8bcc6a"

bspc config border_width         3
#bspc config focused_border_color "#1CFFE9"
bspc config focused_border_color "#FB680F"
bspc config normal_border_color "#282e3a"

xrandr --output Virtual1 --mode 1920x1080

nohup $HOME/.config/bspwm/bspborders &
